spring:
  web:
    resources:
      static-locations: file:uploads/
  mvc:
    static-path-pattern: /images/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: DocLib

  datasource:
    url: jdbc:mysql://localhost:3306/doclib
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    jwt:
      secret-key: verysecretkeyohmygodwhyitissosecretdonttellanybodypleaseee

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail_username
    password: your_gmail_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG

server:
  address: 0.0.0.0
  port: 8080
